### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by samiich** [Someshsw1109/My-Personal-Assistant--David#19]
super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'TrainData.pth'

**Comment by Someshsw1109** [comment]
> ```
> super().__init__(open(name, mode))
>                  ^^^^^^^^^^^^^^^^
> ```
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'TrainData.pth'

When you run Train.py file, then it create TrainData.pth and you can not view or open this file.
when you open Train.py file you can see that i clearly mention that when we run this Train.py it will create a TrainData.pth file
